-- ============================================
-- Script SQL para configurar Supabase
-- Arquitectura Híbrida: Convex + Supabase
-- ============================================

-- Habilitar extensión vector para búsqueda semántica
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- Tabla: news_archive
-- Almacena noticias históricas con embeddings
-- ============================================
CREATE TABLE IF NOT EXISTS news_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tags TEXT[] NOT NULL DEFAULT '{}',
    embedding vector(1536),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para news_archive
CREATE INDEX IF NOT EXISTS idx_news_archive_published_at ON news_archive(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_archive_tags ON news_archive USING GIN(tags);

-- ============================================
-- Tabla: agent_memories
-- Almacena memorias de agentes con embeddings
-- ============================================
CREATE TABLE IF NOT EXISTS agent_memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_convex_id TEXT NOT NULL,
    memory_text TEXT NOT NULL,
    embedding vector(1536),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para agent_memories
CREATE INDEX IF NOT EXISTS idx_agent_memories_agent_id ON agent_memories(agent_convex_id);
CREATE INDEX IF NOT EXISTS idx_agent_memories_created_at ON agent_memories(created_at DESC);

-- ============================================
-- Función RPC: match_news
-- Busca noticias similares por similitud vectorial
-- ============================================
CREATE OR REPLACE FUNCTION match_news(
    query_embedding vector(1536),
    match_threshold float DEFAULT 0.7,
    match_count int DEFAULT 5
)
RETURNS TABLE (
    id BIGINT,
    title TEXT,
    content TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    tags TEXT[],
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        n.id,
        n.title,
        n.content,
        n.published_at,
        n.tags,
        1 - (n.embedding <=> query_embedding) as similarity
    FROM news_archive n
    WHERE n.embedding IS NOT NULL
    ORDER BY n.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- ============================================
-- Función RPC: match_agent_memories
-- Busca memorias similares de un agente específico
-- ============================================
CREATE OR REPLACE FUNCTION match_agent_memories(
    query_embedding vector(1536),
    agent_id TEXT,
    match_threshold float DEFAULT 0.7,
    match_count int DEFAULT 5
)
RETURNS TABLE (
    id BIGINT,
    agent_convex_id TEXT,
    memory_text TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        m.id,
        m.agent_convex_id,
        m.memory_text,
        m.created_at,
        1 - (m.embedding <=> query_embedding) as similarity
    FROM agent_memories m
    WHERE m.agent_convex_id = agent_id
      AND m.embedding IS NOT NULL
    ORDER BY m.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- ============================================
-- Función RPC: search_news_by_tags
-- Busca noticias por tags
-- ============================================
CREATE OR REPLACE FUNCTION search_news_by_tags(
    search_tags TEXT[],
    limit_count int DEFAULT 10
)
RETURNS TABLE (
    id BIGINT,
    title TEXT,
    content TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    tags TEXT[]
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        n.id,
        n.title,
        n.content,
        n.published_at,
        n.tags
    FROM news_archive n
    WHERE n.tags && search_tags
    ORDER BY n.published_at DESC
    LIMIT limit_count;
END;
$$;

-- ============================================
-- Función RPC: get_agent_memories_count
-- Obtiene el conteo de memorias de un agente
-- ============================================
CREATE OR REPLACE FUNCTION get_agent_memories_count(agent_id TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN (
        SELECT COUNT(*)
        FROM agent_memories
        WHERE agent_convex_id = agent_id
    );
END;
$$;

-- ============================================
-- Políticas de seguridad (RLS)
-- Descomentar si necesitas seguridad a nivel de fila
-- ============================================

-- ALTER TABLE news_archive ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE agent_memories ENABLE ROW LEVEL SECURITY;

-- Política para news_archive (lectura pública, escritura solo con service role)
-- CREATE POLICY "Public read access for news_archive"
--     ON news_archive FOR SELECT
--     USING (true);

-- CREATE POLICY "Service role write access for news_archive"
--     ON news_archive FOR ALL
--     USING (auth.role() = 'service_role');

-- Política para agent_memories (lectura pública, escritura solo con service role)
-- CREATE POLICY "Public read access for agent_memories"
--     ON agent_memories FOR SELECT
--     USING (true);

-- CREATE POLICY "Service role write access for agent_memories"
--     ON agent_memories FOR ALL
--     USING (auth.role() = 'service_role');

-- ============================================
-- Comentarios para documentación
-- ============================================
COMMENT ON TABLE news_archive IS 'Archivo de noticias con embeddings para búsqueda semántica';
COMMENT ON TABLE agent_memories IS 'Memorias de agentes con embeddings para recuperación contextual';
COMMENT ON FUNCTION match_news IS 'Busca noticias similares usando similitud coseno de embeddings';
COMMENT ON FUNCTION match_agent_memories IS 'Busca memorias similares de un agente específico';
